###
POST http://localhost:8000/api/v1/create
Content-Type: application/json

{
    "id_kategori":"1",
    "nama_produk":"Fanta",
    "harga":"5000",
    "foto":"fanta.jpg",
    "deskripsi": "minuman soda dengan rasa enak"
}

###
GET http://localhost:8000/api/v1/listProduk

###
GET http://localhost:8000/api/v1/listKategori

###
GET http://localhost:8000/api/v1/detail/1

###
GET http://localhost:8000/api/v1/filter/1

