###
POST http://localhost:8000/api/v1/create
Content-Type: application/json

{
    "id_category":"1",
    "product_name":"Fanta",
    "price":"5000",
    "image":"fanta.jpg",
    "describtion": "minuman soda dengan rasa enak"
}

###
GET http://localhost:8000/

###
GET http://localhost:8000/api/v1/categoryList

###
GET http://localhost:8000/api/v1/detail/1

###
GET http://localhost:8000/api/v1/filter/1

